name: Python CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11' # Replace with your required version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./sklearn-deploy-main/requirements.txt

    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

#      run: |
#        python -m unittest discover -s ./sklearn-deploy-main/tests
#
#    - name: Generate coverage report
#      run: |
#        coverage run -m unittest discover -s ./sklearn-deploy-main/tests
#        coverage report
#        coverage xml
#    
    # we are trying to build the deployment and train image and push to docker hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: parthardas/sklearn-deployment-backend:latest
        context: .
        file: ./sklearn-deploy-main/deployments/api.Dockerfile
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: parthardas/sklearn-deployment-frontend:latest
        context: .
        file: ./sklearn-deploy-main/deployments/frontend.Dockerfile
